// Code generated by ogen, DO NOT EDIT.
package api

type CreateUserRes interface {
	createUserRes()
}

type LoginRes interface {
	loginRes()
}

type LogoutRes interface {
	logoutRes()
}

type RefreshTokenRes interface {
	refreshTokenRes()
}
