// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateUserOperation   OperationName = "CreateUser"
	LoginOperation        OperationName = "Login"
	LogoutOperation       OperationName = "Logout"
	PingOperation         OperationName = "Ping"
	RefreshTokenOperation OperationName = "RefreshToken"
)
