// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateAccountOperation         OperationName = "CreateAccount"
	CreateUserOperation            OperationName = "CreateUser"
	GetAccountOperation            OperationName = "GetAccount"
	GetBalanceOperation            OperationName = "GetBalance"
	GetStatementOperation          OperationName = "GetStatement"
	GetTransactionOperation        OperationName = "GetTransaction"
	GetTransactionHistoryOperation OperationName = "GetTransactionHistory"
	GetUserAccountsOperation       OperationName = "GetUserAccounts"
	LoginOperation                 OperationName = "Login"
	LogoutOperation                OperationName = "Logout"
	PingOperation                  OperationName = "Ping"
	RefreshTokenOperation          OperationName = "RefreshToken"
	ReplenishOperation             OperationName = "Replenish"
	TransferOperation              OperationName = "Transfer"
	UpdateAccountStatusOperation   OperationName = "UpdateAccountStatus"
)
