// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateAccount implements createAccount operation.
	//
	// Creates a new bank account for a user.
	//
	// POST /accounts
	CreateAccount(ctx context.Context, req *CreateAccountRequest) (CreateAccountRes, error)
	// CreateUser implements createUser operation.
	//
	// Creates a new user and assigns initial roles.
	//
	// POST /users
	CreateUser(ctx context.Context, req *CreateUserRequest) (CreateUserRes, error)
	// GetAccount implements getAccount operation.
	//
	// Returns account details by ID.
	//
	// GET /accounts/{account_id}
	GetAccount(ctx context.Context, params GetAccountParams) (GetAccountRes, error)
	// GetBalance implements getBalance operation.
	//
	// Returns current balance of an account.
	//
	// GET /accounts/{account_id}/balance
	GetBalance(ctx context.Context, params GetBalanceParams) (GetBalanceRes, error)
	// GetStatement implements getStatement operation.
	//
	// Returns ledger statement for an account in a given time range.
	//
	// GET /accounts/{account_id}/statement
	GetStatement(ctx context.Context, params GetStatementParams) (GetStatementRes, error)
	// GetTransaction implements getTransaction operation.
	//
	// Returns transaction details by ID.
	//
	// GET /transactions/{transaction_id}
	GetTransaction(ctx context.Context, params GetTransactionParams) (GetTransactionRes, error)
	// GetTransactionHistory implements getTransactionHistory operation.
	//
	// Returns transaction history for an account.
	//
	// GET /accounts/{account_id}/transactions
	GetTransactionHistory(ctx context.Context, params GetTransactionHistoryParams) (GetTransactionHistoryRes, error)
	// GetUserAccounts implements getUserAccounts operation.
	//
	// Returns all accounts belonging to a user.
	//
	// GET /users/{user_id}/accounts
	GetUserAccounts(ctx context.Context, params GetUserAccountsParams) (GetUserAccountsRes, error)
	// Login implements login operation.
	//
	// Authenticates user by login and password.
	//
	// POST /auth/login
	Login(ctx context.Context, req *LoginRequest) (LoginRes, error)
	// Logout implements logout operation.
	//
	// Revokes refresh token and closes related session.
	//
	// POST /auth/logout
	Logout(ctx context.Context, req *LogoutRequest) (LogoutRes, error)
	// Ping implements ping operation.
	//
	// Ping endpoint.
	//
	// GET /ping
	Ping(ctx context.Context) (*PingResponse, error)
	// RefreshToken implements refreshToken operation.
	//
	// Rotates refresh token and returns a new token pair.
	//
	// POST /auth/refresh
	RefreshToken(ctx context.Context, req *RefreshTokenRequest) (RefreshTokenRes, error)
	// Replenish implements replenish operation.
	//
	// Replenishes (credits) an account with the given amount.
	//
	// POST /transactions/replenish
	Replenish(ctx context.Context, req *ReplenishRequest) (ReplenishRes, error)
	// Transfer implements transfer operation.
	//
	// Transfers funds between two accounts.
	//
	// POST /transactions/transfer
	Transfer(ctx context.Context, req *TransferRequest) (TransferRes, error)
	// UpdateAccountStatus implements updateAccountStatus operation.
	//
	// Updates the status of an account.
	//
	// PATCH /accounts/{account_id}/status
	UpdateAccountStatus(ctx context.Context, req *UpdateAccountStatusRequest, params UpdateAccountStatusParams) (UpdateAccountStatusRes, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
