// Code generated by ogen, DO NOT EDIT.
package api

type CreateAccountRes interface {
	createAccountRes()
}

type CreateUserRes interface {
	createUserRes()
}

type GetAccountRes interface {
	getAccountRes()
}

type GetBalanceRes interface {
	getBalanceRes()
}

type GetStatementRes interface {
	getStatementRes()
}

type GetTransactionHistoryRes interface {
	getTransactionHistoryRes()
}

type GetTransactionRes interface {
	getTransactionRes()
}

type GetUserAccountsRes interface {
	getUserAccountsRes()
}

type LoginRes interface {
	loginRes()
}

type LogoutRes interface {
	logoutRes()
}

type RefreshTokenRes interface {
	refreshTokenRes()
}

type ReplenishRes interface {
	replenishRes()
}

type TransferRes interface {
	transferRes()
}

type UpdateAccountStatusRes interface {
	updateAccountStatusRes()
}
